class.tx_odsosm_leaflet.php
res/leaflet-plugins/bower.json
res/leaflet-plugins/layer/vector/KML.js
res/leaflet-plugins/package.json

leaflet-plugins 1.3.3
only load one base layer at a time

leaflet-plugins update and a baselayer fix for leaflet

---

Classes/Div.php

Move javascript libs to footer section.

---

Classes/Controller/PluginController.php
Classes/Div.php

Changes for TYPO3 9

---

Classes/Provider/Openlayers.php

This is an old feature request from forge:
https://forge.typo3.org/issues/48744
Which has been fixed but never merged in PR #5.
This patch takes the ideas from #5 and applies it to the current code.
For tt_address and fe_users records it is working like this.

Use already set coordinate in coordinatesPicker.

---

Configuration/TCA/Overrides/fe_groups.php
Configuration/TCA/Overrides/fe_users.php
Configuration/TCA/Overrides/sys_category.php

Add defaults in TCA because of DB strict mode

---

Classes/Div.php

GeneralUtility::devLog() does not exist in TYPO3 10 anymore. This removes the usage.

Use logger instead of deprecated/removed devLog()

---

Classes/Provider/Leaflet.php
Classes/Provider/Openlayers.php
Classes/Provider/Staticmap.php
Classes/TceMain.php
Configuration/TCA/tx_odsosm_vector.php
Resources/Private/Language/locallang_db.xml
ext_tables.sql

This adds the possibility to add a GeoJSON file to the tx_odsosm_vector record as it is done with markers and tracks.
FeatureCollections are supported now, as it is given to Leaflet as is. Haven't checked it with OpenLayers yet.

Add possibility to add GeoJSON file with FeatureCollections.

---

Classes/Div.php

This will fix #71.
@sypets please check the functionality and add another issue if it doesn't work. In this case, please describe your use case, to make it reproducible for me. 
Thank you for reporting!

Deprecation: #85543 - Replace usage of ['TSFE']->sys_language_content

---

Classes/Provider/Leaflet.php

This fixes the usage of markercluster.

Fix path to leaflet library

---

Classes/Controller/PluginController.php

This will fix #81. 
Thank you @MichiSpandl for reporting!

Fix wrong array index.

---

Classes/Provider/Leaflet.php

Fix popups for tx_odsosm_vector

---

Classes/Provider/Leaflet.php

Fix broken icon URL

---

Classes/Div.php

The property might not always be set.

Bugfix fix PHP 8 incompaibility

---

ext_localconf.php

Fix icon identifer in CE wizard

---

Configuration/Extbase/Persistence/Classes.php
Configuration/TCA/Overrides/fe_groups.php
Configuration/TCA/Overrides/fe_users.php
Configuration/TCA/Overrides/sys_category.php
Configuration/TCA/Overrides/sys_template.php
Configuration/TCA/Overrides/tt_content.php
Configuration/TCA/Overrides/tx_calendarize_domain_model_event.php
Configuration/TypoScript/setup.typoscript
Documentation/Administrators/Index.rst
Documentation/Editors/Index.rst
Documentation/Introduction/Index.rst
Documentation/Settings.cfg
Documentation/Tutorial/Index.rst
ext_localconf.php

- Should fix #101 
- Some fixes for the documentation

Prepare release 4.1

---

Classes/Updates/MigrateSettings.php

The following checks were added to handle possible situations due to inconsistent or corrupt content.
1. Check if pi_flexform is not NULL or empty and skip the record.
2. Do not perform an UPDATE on a record if there is nothing to be changed.
In case a pi_flexform is in fact NULL or empty, this should be fixed manually but it will now not cause the upgrade wizard to crash.
Resolves: #105

Add some checks in upgrade wizard MigrateSettings

---

Classes/Div.php
Classes/TceMain.php
Classes/Updates/FileLocationUpdater.php
Classes/Updates/MigrateSettings.php
ext_localconf.php

This will fix #104 and #105.
Some more issues with PHP 8.1 should be fixed, too.

Harden the migration settings wizard

---

Classes/Controller/PluginController.php

Fix enable_scrollwheelzoom and enable_dragging setting if unset

---

Configuration/TCA/Overrides/fe_groups.php
Configuration/TCA/Overrides/sys_category.php

Add internal_type for TCA configuration of fe_groups and sys_category

---

Classes/Provider/Openlayers.php
Configuration/TypoScript/setup.typoscript
Documentation/Administrators/Index.rst

Extend TypoScript to get image for popups from fe_users and tt_address records.

---

ChangeLog
Classes/Updates/FileLocationUpdater.php
ext_emconf.php

Fix #147: do not define variable $logger again

---

Classes/Controller/PluginController.php

Fix custom IMAGE marker

---

Classes/EventListener/CalendarizeOdsOsmSqlListener.php
Configuration/Services.yaml
ext_tables.sql

@albig see verdigado issue 4675

create calendarize fields only if extension is loaded - 4.1.x

---

Classes/EventListener/CalendarizeOdsOsmSqlListener.php
Configuration/Services.yaml
ext_tables.sql

@albig see verdigado issue 4675

create calendarize fields only if extension is loaded

---

Classes/Div.php
Classes/Evaluation/LonLat.php
Classes/Provider/Leaflet.php
Classes/Provider/Openlayers.php
Classes/TceMain.php
Classes/Updates/FileLocationUpdater.php
Resources/Private/Extensions/Calendarize/Templates/Calendar/Detail.html
ext_localconf.php

- Add missing visibility to methods
- Indent code correctly
- Remove unused variables
- Sort namespaces
- Remove unused namespaces

[TASK] Code cleanup

---

Configuration/TCA/tx_odsosm_layer.php
Configuration/TCA/tx_odsosm_track.php
Configuration/TCA/tx_odsosm_vector.php

Apply rector rule SimplifyCheckboxItemsTCARector (https://review.typo3.org/c/Packages/TYPO3.CMS/+/72056)
Resolves: #171

[TASK] Apply TYPO3 Rector rule SimplifyCheckboxItemsTCARector

---

Classes/TceMain.php

[BUGFIX] Fix 180: Do not overwrite "address" field with entire address

---

ext_localconf.php

This is supported since TYPO3 11.4

[TASK] Register icons through Symfony container only
